father(vladimir,anton).
mother(tatiana,anton).
mother(zoya,tatiana).
mother(zoya,olga).
father(alexandr,tatiana).
father(alexandr,olga).
mother(olga,eugeny).
mother(olga,svetlana).
father(viktor,svetlana).
father(eugeny,sofia).
mother(angela,sofia).
father(georgy,eugeny).
father(sergay,irina).
father(sergay,galina).
father(sergay,vladimir).
mother(maria,irina).
mother(maria,galina).
mother(maria,vladimir).
mother(irina,vadim).
mother(galina,inna).
father(semion,vadim).
father(valery,inna).
